# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-20 07:55
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('KIT', 'kitchen'), ('CLI', 'client')], max_length=7, verbose_name='Type of check')),
                ('order', django.contrib.postgres.fields.jsonb.JSONField()),
                ('status', models.CharField(choices=[('N', 'new'), ('R', 'rendered'), ('p', 'printed')], max_length=8, verbose_name='Status of check')),
                ('pdf_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('api_key', models.CharField(max_length=10)),
                ('check_type', models.CharField(choices=[('KIT', 'kitchen'), ('CLI', 'client')], max_length=7)),
                ('point_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='check',
            name='printer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Printer'),
        ),
    ]
