# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-20 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='status',
            field=models.CharField(choices=[('N', 'new'), ('R', 'rendered'), ('p', 'printed')], max_length=1, verbose_name='Status of check'),
        ),
        migrations.AlterField(
            model_name='check',
            name='type',
            field=models.CharField(choices=[('KIT', 'kitchen'), ('CLI', 'client')], max_length=3, verbose_name='Type of check'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='check_type',
            field=models.CharField(choices=[('KIT', 'kitchen'), ('CLI', 'client')], max_length=3),
        ),
    ]
