# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-20 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190320_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='pdf_file',
            field=models.FileField(max_length=300, upload_to=''),
        ),
    ]
