# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-20 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190320_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printer',
            name='api_key',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
